name: production release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  release:
    name: Build & Release APIs
    runs-on: ubuntu-latest
    steps:
      - run: echo "GOPRIVATE=github.com/env-io/*" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - name: Application Build
        env:
          TOKEN: ${{ secrets.GO_SECRET }}
        run: |
          git config --global url."https://naufaldinta13:${{ secrets.TOKEN }}@github.com".insteadOf "https://github.com"
          echo "GO111MODULE=on" >> $GITHUB_ENV
          go mod tidy
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build
      - name: Release
        uses: mr-smithers-excellent/docker-build-push@v5
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          image: liat.platform.usergroup
          registry: ${{ secrets.AWS_ECR_REGISTRY }}
          tags: latest
          buildArgs: COMMIT=${GITHUB_SHA}
